version: "3.9"
   
services:
 
  db:
    image: postgres
    restart: always
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "6000:6000"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db


  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend/
    ports:
      - "3000:3000"
    depends_on:
      - backend
