# Generated by Django 4.0.3 on 2022-04-23 14:57

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to=post.models.image_file_path),
        ),
    ]
